# cray toolchain
CXX=CC
CC=cc -lcray-c++-rts
F90=ftn


PAPI_PATH=/opt/cray/papi/5.4.0.1
PAPIWRAP_PATH=../
#PAPI_LIB_PATH=$(PAPI_PATH)/lib
#LDFLAGS=$(PAPIWRAP_PATH)/libpapi_wrap.a $(PAPI_LIB_PATH)/libpapi.a $(PAPI_LIB_PATH)/libpfm.a -lstdc++

LDFLAGS_FORTRAN=-L$(PAPIWRAP_PATH) -lpapi_wrap
#LDFLAGS_FORTRAN+=-L$(PAPI_LIB_PATH) -lpapi -lpfm
LDFLAGS_FORTRAN+=-L/opt/cray/cce/8.2.1/CC/x86-64/lib/x86-64/ -lcray-c++-rts
LDFLAGS_FORTRAN+=-I..

LDFLAGS=-L$(PAPIWRAP_PATH) -lpapi_wrap

IFLAGS=-I$(PAPI_PATH)/include -I..

CXXFLAGS=$(IFLAGS)
CCFLAGS=$(IFLAGS)

all: matmul dot saxpy stream

matmul: matmul.cpp
	$(CXX) $(CXXFLAGS) matmul.cpp $(LDFLAGS) -o matmul

dot: dot.c
	$(CC) $(CCFLAGS) dot.c $(LDFLAGS) -o dot

saxpy: saxpy.f90
	$(F90) $(F90FLAGS) $(LDFLAGS_FORTRAN) saxpy.f90 -o saxpy

static: static.c
	$(CC) $(CCFLAGS) static.c $(LDFLAGS) -o static

stream: stream.cu
	nvcc -arch=sm_35 $(CCFLAGS) stream.cu $(LDFLAGS) -o stream

clean:
	rm -f dot matmul saxpy static stream

