# choose mpi wrapper if required
ifdef PW_MPI
    CC=mpixlc_r
    CXX=mpixlcxx_r
else
    CC=bgxlc_r
    CXX=bgxlc++_r
endif
# add openmp flags if required
CCFLAGS=-qsimd=auto
ifdef PW_OPENMP
    CCFLAGS+=-qsmp=omp
endif

PAPI_PATH=/gpfs/bbp.cscs.ch/home/cumming/install/papi
PAPIWRAP_PATH=../
PAPI_LIB_PATH=$(PAPI_PATH)/lib
LDFLAGS=-L$(PAPI_LIB_PATH) -lpapi_wrap -L$(PAPIWRAP_PATH) -lpapi  -lrt -lstdc++
IFLAGS=-I$(PAPI_PATH)/include -I..

CCFLAGS+=$(IFLAGS)

all: matmul dot static

matmul: matmul.cpp
	$(CXX) $(CCFLAGS) matmul.cpp $(LDFLAGS) -o matmul

dot: dot.c
	$(CC) $(CCFLAGS) dot.c $(LDFLAGS) -o dot

static: static.c
	$(CC) $(CCFLAGS) static.c $(LDFLAGS) -o static

clean:
	rm -f dot matmul static

